### PR TITLE
Enable Actions CI for go&rust

### PR DESCRIPTION
**Pull request by armfazh**
Use github Actions CI for running tests
Fixes: #20

### CODE REVIEW

**Comment by armfazh** [comment]
Currently Rust is failing due to: 
https://github.com/alxdavids/ring-ecc/issues/1
After this change be applied, the rust compilation will succeed.

**Comment by alxdavids** [comment]
ring-ecc should now be fixed if it is possible to re-run Rust CI?

**Comment by alxdavids** [comment]
I've re-run it and the previous error no longer occurs, but now it seems like the CI can't find the test vector files?

**Comment by armfazh** [comment]
Ready to go.

**Pull request merged**
